server:
  port: 8081
spring:
  application:
    name: seoulMate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.105.117.218:3306/SEOULMATE
    username: "seoulmate"
    password: "0000"
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    show-sql: true

  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      httpclient:
        enabled: true
        connection-timeout: 5000 # ?? ?? ? ?? ?? ??? 5? ?? ? connection-time out ??
        ok-http:
          read-timeout: 5000 # ?? ???? ?? ??? 5? ?? ? read-time out ??
#    gcp:
#      credentials:
#        location: /Users/gimsehyeon/workspace/seoul/seoulmate-455013-41dba0a867c2.json
seoul:
  key: 50486d5a4b74746138344e544e4152
  url: http://openapi.seoul.go.kr:8088/
feign:
  client:
    config:
      default:
        loggerLevel: FULL
naver:
  clientId: NiZnI_maT5yPdLE9Qa2W
  clientSecret: bDyNn9hqkG
  url: https://openapi.naver.com
logging:
  level:
    com.sm.seoulmate: DEBUG
    feign.Logger: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
google:
  cloud:
    key: AIzaSyCZ6CyuinSyOUc3-RLxJiPsy_pM_QR1sUU
#    feign.Logger.Level: FULL
