spring:
  application:
    name: seoulMate
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8081
seoul:
  key: 50486d5a4b74746138344e544e4152
  url: http://openapi.seoul.go.kr:8088/
