---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local
  application:
    name: seoulMate
  main:
    allow-bean-definition-overriding: true
  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.105.147.53:3306/SEOUL
    username: "seoulmate"
    password: "0000"
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    show-sql: true
  cloud:
    openfeign:
      httpclient:
        enabled: true
        connection-timeout: 5000 # ?? ?? ? ?? ?? ??? 5? ?? ? connection-time out ??
        ok-http:
          read-timeout: 5000 # ?? ???? ?? ??? 5? ?? ? read-time out ??
swagger:
  server:
    url: http://localhost:8081
seoul:
  key: 50486d5a4b74746138344e544e4152
  url: http://openapi.seoul.go.kr:8088/
feign:
  client:
    config:
      default:
        loggerLevel: FULL
tour:
  key: WCNu35iMNG82k9c5hC0QVp4T1FMe0sOm5yklhUizrnFSAC7IGsvn1w%2BjplO7oGomxeLwcc2PgaxGbFBthVkaAw%3D%3D
  url: http://apis.data.go.kr/B551011/KorService1
naver:
  clientId: NiZnI_maT5yPdLE9Qa2W
  clientSecret: bDyNn9hqkG
  url: https://openapi.naver.com
  map:
    clientId: p0wwpabrrh
    clientSecret: A9zLQrFNIAM5YfOOmbAXxIghxJyTIOZangMZzlP8
    url: https://maps.apigw.ntruss.com/map-geocode
logging:
  level:
    com.sm.seoulmate: DEBUG
    com.zaxxer.hikari: DEBUG
    feign.Logger: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
apple:
  filePath: /Users/gimsehyeon/workspace/seoul/PopPopSeoulKey.p8
---
server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: seoulMate
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.105.147.53:3306/SEOUL
    username: "seoulmate"
    password: "0000"
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    show-sql: true
  cloud:
    openfeign:
      httpclient:
        enabled: true
        connection-timeout: 5000 # ?? ?? ? ?? ?? ??? 5? ?? ? connection-time out ??
        ok-http:
          read-timeout: 5000 # ?? ???? ?? ??? 5? ?? ? read-time out ??
swagger:
  server:
    url: https://popseoul.co.kr
seoul:
  key: 50486d5a4b74746138344e544e4152
  url: http://openapi.seoul.go.kr:8088/
feign:
  client:
    config:
      default:
        loggerLevel: FULL
tour:
  key: WCNu35iMNG82k9c5hC0QVp4T1FMe0sOm5yklhUizrnFSAC7IGsvn1w%2BjplO7oGomxeLwcc2PgaxGbFBthVkaAw%3D%3D
  url: http://apis.data.go.kr/B551011/KorService1
naver:
  clientId: NiZnI_maT5yPdLE9Qa2W
  clientSecret: bDyNn9hqkG
  url: https://openapi.naver.com
  map:
    clientId: p0wwpabrrh
    clientSecret: A9zLQrFNIAM5YfOOmbAXxIghxJyTIOZangMZzlP8
    url: https://maps.apigw.ntruss.com/map-geocode
apple:
  filePath: /workspace/PopPopSeoulKey.p8
logging:
  level:
    com.sm.seoulmate: DEBUG
    com.zaxxer.hikari: DEBUG
    feign.Logger: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
